/**
 * الغرض: عقدُ المخطّط: أسماءُ دوالّ القاعدة وجداولِها التي يستدعيها كودُ التشغيل،
 *   ليتحقّق فحصُ الجهوزيّة من وجودها في القاعدة الموصولة فعلاً.
 * الحالة: مولَّد آلياً — لا يُحرَّر يدوياً. شغّل: bun run scripts/check-schema-contract.ts --write
 * ينتمي إلى: packages/infrastructure/db
 * يُتوقع أن يستخدمه لاحقاً: packages/infrastructure/db/schema-guard.ts وفحص /ready
 * ملاحظات مستقبلية: الغيابُ هنا يعني خطأَ تشغيلٍ حقيقياً لا نقصاً نظرياً، فالقائمةُ
 *   محصورةٌ بما يناديه الكودُ لا بكلّ ما في الترحيلات.
 */

/** دوالُّ القاعدة التي يناديها كودُ التشغيل. */
export const CONTRACT_FUNCTIONS: readonly string[] = [
  "admin_set_driver_verification",
  "admin_set_user_blocked",
  "admin_update_city_group_ids",
  "admin_update_setting",
  "advance_unsubscribed_negotiation",
  "attach_support_ticket_card",
  "cancel_broadcast",
  "cancel_order_by_rider",
  "cancel_subscription",
  "claim_broadcast_recipients",
  "claim_ride",
  "claim_safety_incident",
  "claim_safety_incident_delivery",
  "claim_subscription_notices",
  "claim_support_ticket",
  "claim_telegram_update",
  "close_admin_session",
  "close_unsubscribed_negotiation",
  "complete_ride",
  "confirm_payment",
  "confirm_webhook_payment",
  "consume_admin_login_code",
  "count_broadcast_audience",
  "create_broadcast",
  "create_payment",
  "create_subscription_wallet",
  "deactivate_stale_availability",
  "escalate_order",
  "expire_due_subscriptions",
  "expire_tracking_tokens",
  "finish_broadcast_delivery",
  "finish_safety_incident_delivery",
  "finish_subscription_notice",
  "finish_telegram_update",
  "flag_rating",
  "get_reputation_summary",
  "get_setting_number",
  "get_support_ticket_context",
  "get_tracking_position",
  "get_user_language",
  "grant_bootstrap_admin",
  "issue_admin_login_code",
  "issue_subscription_invoice",
  "issue_tracking_token",
  "list_stale_pending_payments",
  "mark_escalation_delivered",
  "open_admin_session",
  "open_offer_round",
  "open_support_ticket",
  "open_unsubscribed_cycle",
  "plan_upgrade_quote",
  "recompute_rating_averages",
  "record_agent_outcome",
  "record_attendance",
  "record_job_heartbeat",
  "record_payment_checkout",
  "record_payment_provider_reference",
  "record_subscription_warning",
  "record_webhook_event",
  "refund_subscription_payment",
  "register_unsubscribed_claim",
  "resolve_safety_incident",
  "resolve_support_ticket",
  "resume_subscription",
  "revoke_order_tracking_tokens",
  "revoke_tracking_token",
  "set_user_language",
  "settle_subscription_wallet_system_error",
  "settle_unsubscribed_negotiation",
  "start_ride",
  "start_trial",
  "submit_rating",
  "subscription_wallet_balance",
  "subscriptions_expiring_soon",
  "top_up_subscription_wallet",
  "touch_admin_session",
  "trigger_sos",
  "update_driver_city",
  "update_rider_city",
  "upgrade_plan",
];

/** جداولُ القاعدة التي يقرؤها كودُ التشغيل أو يكتب فيها مباشرةً. */
export const CONTRACT_TABLES: readonly string[] = [
  "agent_decisions",
  "attendance_log",
  "audit_log",
  "broadcast_campaigns",
  "broadcast_recipients",
  "cities",
  "db_backups",
  "driver_availability",
  "driver_capabilities",
  "drivers",
  "job_heartbeats",
  "order_offers",
  "orders",
  "payment_transactions",
  "platform_settings",
  "ratings",
  "riders",
  "subscriptions",
  "support_tickets",
  "tracking_sessions",
  "unsubscribed_claims",
  "unsubscribed_negotiations",
  "users",
];
